### ISSUE TITLE
Everything but dashboard works: "No such file or directory"

### ISSUE THREAD

**Issue by ShrootBuck** [saleor/saleor-dashboard#2647]
I've done the entire installation process up until `docker-compose up`. When I run that, the storefront and core work properly, but I keep getting the following console for the dashboard:

![image](https://user-images.githubusercontent.com/70227235/203471574-08e9e00f-016a-48c0-8872-e1ddf6a657a8.png)

Any ideas?

**Comment by NikunjPansuriya** [comment]
@krzysztofzuraw 
Dashboard also not working for me. Below are the docker version details.
Docker:- Docker version 20.10.21, build baeda1f
Docker-compose:- Docker Compose version v2.12.2

<img width="1108" alt="Screen Shot 2022-11-23 at 3 11 44 PM" src="https://user-images.githubusercontent.com/20836849/203516020-1e61d895-55fc-4d7f-ac1f-f2b1625b8014.png">

<img width="1280" alt="Screen Shot 2022-11-23 at 3 11 08 PM" src="https://user-images.githubusercontent.com/20836849/203516036-4d073bbc-387f-4d78-beff-bc45c67a4ce5.png">

**Comment by krzysztofzuraw** [comment]
@NikunjPansuriya please check the latest changes from https://github.com/saleor/saleor-platform - I've just fixed bug with docker-compose volumes 😄

**Comment by NikunjPansuriya** [comment]
Thanks @krzysztofzuraw Its working now :grinning:

**Comment by ShrootBuck** [comment]
Working as well! Sorry for the issue

**Comment by ShrootBuck** [comment]
Still doesn't seem to be working for me. Getting the same error. I'm on the latest docker version

**Comment by Gregorek85** [comment]
Hi, I have the same issue as ShrootBuck. Docker Compose version v2.12.0, Docker Version:20.10.20

**Comment by krzysztofzuraw** [comment]
I will look into this - @Gregorek85 are you on Windows as well? 🤔

**Comment by Gregorek85** [comment]
@krzysztofzuraw Yes, Windows

**Comment by krzysztofzuraw** [comment]
After investigation, it turns out that problem is in line endings - `50-replace-api-url.sh` should have an `LF` line ending (as it will be executed inside Docker) and by default, git will convert line endings to `CRLF` for windows.

**Quick fix:** Edit `saleor-platform/saleor-dashboard/nginx/replace-api-url.sh` to have `LF` ending - see screenshot how to do this in VSCode:

https://user-images.githubusercontent.com/9116238/203757571-2b902de7-3c12-48eb-bf24-f10eb49bf0b6.mp4

I will prepare a proper fix in PR but you will have to clone the repository one more time in order for the fixes to work.

**Comment by Gregorek85** [comment]
Works, thanks!

**Comment by robertjawoods** [comment]
![image](https://user-images.githubusercontent.com/19418761/204069175-33ffd866-2277-4edf-8dff-05b9f980062c.png)
 This still seems to be occurring for me. I have double checked that I have pulled the latest version of the dashboard, although the latest version was already installed when I followed the installation instructions. 

![image](https://user-images.githubusercontent.com/19418761/204069212-9185e380-db93-456c-8965-14c80e915c22.png)
I can see the commit for the fix in the git log, I have ran `docker-compose build` to rebuild, however I am still encountering the original error.

**Comment by ShrootBuck** [comment]
Still happening for me as well. I just ran `git config --global core.autocrlf false` so that git doesn't automatically convert and it works now.

**Comment by robertjawoods** [comment]
@ShrootBuck - to do that, should I run your command then clone the repos again?

**Comment by ShrootBuck** [comment]
Yes, running it would require re-cloning the repos. As for side effects, I doubt anything unpredictable could come from this. Not sure though.

**Comment by krzysztofzuraw** [comment]
I plan to release #2665 today in `3.8` and update https://github.com/saleor/saleor-platform with a proper tag so cloning **new** repo should have right line endings for `.sh` files. 

If you have already cloned the repository and won't like to do it again you can change the line ending as described in https://github.com/saleor/saleor-dashboard/issues/2647#issuecomment-1326234420.

**Comment by AlexisHeap** [comment]
Hello everyone, @krzysztofzuraw would do you me a favour, please? I have followed this entire conversation but I still can't resolve it, I did this process:

I did this and I saved it: 
![issue replace api sh](https://user-images.githubusercontent.com/119627818/205188397-4f29f772-ac35-48d8-95ee-2e34aba9d5b0.png)

1. I clonned the repository again but i didn't know if i have to clone either the saleor-dashboard (https://github.com/saleor/saleor-dashboard.git) repository or the whole repository, it doesn't work.  

2. I also follow this instruction from default: # Replaces the API_URL from the bundle's index.html file with the $API_URL env var. and this was as follows:

![issue replace api sh 2](https://user-images.githubusercontent.com/119627818/205189272-3b083f0f-707a-4f44-919c-55ce89ece7f4.png)

I've already done both ways (#2) and without that.

I have this images for visualization:

![docker saleor-dashboard error](https://user-images.githubusercontent.com/119627818/205190063-9464854e-e6ce-477d-b7b0-e3843ca4d0b1.png)

![docker saleor-dashboard error 2](https://user-images.githubusercontent.com/119627818/205190170-941ab1bb-ab55-4b01-860d-587736451297.png)

inside of conf.d folder is the default.conf --> ![location of default conf](https://user-images.githubusercontent.com/119627818/205190407-eb481058-14e7-4c2d-9ae0-807b53753025.png)

I would appreciate, regards in advance

**Comment by krzysztofzuraw** [comment]
Hi @AlexisHeap  and thank you for the comment 👋🏻

Can you try the latest version of https://github.com/saleor/saleor-platform? We just merged changes from the dashboard. You will need to clone the repository one more time - please check if e.g VSCode shows a proper tag (`3.8.7`) for the dashboard. See the screenshot for more info:

![CleanShot 2022-12-02 at 09 08 31@2x](https://user-images.githubusercontent.com/9116238/205245947-31bb1009-74cc-4358-b796-6554af79b311.jpg)
